Combined grade/refresh and grades, removed backend caching #115
AStA-HTWG-Konstanz/backend pull request #116
Opened 2019-07-20 13:51 UTC by da721wol

2019-07-20 15:43 UTC, Sebi1006 approved these changes

2019-07-22 10:59 UTC, Alesfatalis requested changes
Route hat keinen Schutz wie oft sie aufgerufen wird. Qisserver kann mit wiederholten Anfragen dann überlastet werden. Caching war eigentlich ein wirksamer Schutz dagegen. Es kann auch nicht davon ausgegangen werden das nur die App die API in Zukunft nutzt, da die API jetzt öffentlich Dokumentiert ist.

2019-07-22 13:09 UTC, da721wol commented
Könnten wir name + letzter Anfragezeitpunkt cachen, aber ohne die noten selber? Wenn dann ne neue Anfrage kommt überprüfen wir ob die innerhalb der letzten stunde oder so schon durchegführt wurde und geben dann halt entsprechend nichts zurück. Dann müsste das Frontend kein token speichern und wir hätten eine immer gleiche anfrage mit zwei möglichen antworten

2019-07-22 13:48 UTC, Alesfatalis commented
Anstatt ein weiteres Caching einzubauen wieso nicht den alten Stand lassen und einen Token übergeben. Ist ja einfach nur ein zufallsgenerierter String der mit den Zugangsdaten in der App abgelegt werden kann. Die Zugangsdaten werden ja eh beim Aufruf des Endpoints benötigt und da kann man direkt den Token mit abfragen. Die `grades-refresh`Route wäre ja dann sobald @MaAsche  rate-limit gemerged ist geschützt. `Grades-refresh` kann ja aus sicht der App nur den Status `ok` und `Error` annehmen. `Wrong credentials`sollte ja in der App nicht vorkommen. Für den `grades-call`gibt es ja auch nur 3 Zustände `ok`, `error` und `keine Daten`. 

Insgesamt ist mir der Grund und die Sinnhaftigkeit für die Änderung im Verhältnis zum Aufwand hier nicht ganz klar.

2019-07-22 13:59 UTC, da721wol commented
Weil so das frontend 2 verschiedene Anfragen schicken muss, einmal refresh und einmal grades. So muss das frontend entscheiden, wann es aktuelle Daten haben will, bzw. einfach jedes mal 2 Anfragen rausschicken wenn es grades haben will. So sollte aber keine API aufgebaut sein. Stattdessen sollte das backend das übernehmen. Wir könnten auch nen ähnlichen cache aufbau wie jetzt beibehalten und einfach den refresh zu grades hinzufügen. Bei jeder grades anfrage wird dann nach @MaAsche prinzip geschaut ob refreshed werden soll oder nicht. Dann wär halt der Token dabei, aber der ist eh nicht so kritisch. Und für das frontend wäre es nur noch eine Anfrage

2019-07-22 14:01 UTC, da721wol commented
Das wär dann auch kein großer Aufwand, da man einfach nur grades-refresh vorher aufruft und die entsprechende route entfernt

2019-07-22 14:02 UTC, Alesfatalis commented
Alles klar dann könnt ihr das so umsetzen. Wichtig ist aber das alle Möglichkeiten den Qisserver zu überlasten blockiert werden.

2019-07-23 10:47 UTC, closed without merging